//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by hand (controller-gen not available). DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetSpec) DeepCopyInto(out *BudgetSpec) {
	*out = *in
	if in.AlertThresholds != nil {
		in, out := &in.AlertThresholds, &out.AlertThresholds
		*out = make([]float64, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetSpec.
func (in *BudgetSpec) DeepCopy() *BudgetSpec {
	if in == nil {
		return nil
	}
	out := new(BudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceMixSpec) DeepCopyInto(out *InstanceMixSpec) {
	*out = *in
	if in.AllowedInstanceTypes != nil {
		in, out := &in.AllowedInstanceTypes, &out.AllowedInstanceTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceMixSpec.
func (in *InstanceMixSpec) DeepCopy() *InstanceMixSpec {
	if in == nil {
		return nil
	}
	out := new(InstanceMixSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertingChannelSpec) DeepCopyInto(out *AlertingChannelSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertingChannelSpec.
func (in *AlertingChannelSpec) DeepCopy() *AlertingChannelSpec {
	if in == nil {
		return nil
	}
	out := new(AlertingChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SilenceWindowSpec) DeepCopyInto(out *SilenceWindowSpec) {
	*out = *in
	in.Start.DeepCopyInto(&out.Start)
	in.End.DeepCopyInto(&out.End)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SilenceWindowSpec.
func (in *SilenceWindowSpec) DeepCopy() *SilenceWindowSpec {
	if in == nil {
		return nil
	}
	out := new(SilenceWindowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertingSpec) DeepCopyInto(out *AlertingSpec) {
	*out = *in
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = make([]AlertingChannelSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SilenceWindows != nil {
		in, out := &in.SilenceWindows, &out.SilenceWindows
		*out = make([]SilenceWindowSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertingSpec.
func (in *AlertingSpec) DeepCopy() *AlertingSpec {
	if in == nil {
		return nil
	}
	out := new(AlertingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyCondition) DeepCopyInto(out *PolicyCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyCondition.
func (in *PolicyCondition) DeepCopy() *PolicyCondition {
	if in == nil {
		return nil
	}
	out := new(PolicyCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FinancialPolicySpec) DeepCopyInto(out *FinancialPolicySpec) {
	*out = *in
	in.Budget.DeepCopyInto(&out.Budget)
	if in.InstanceMix != nil {
		in, out := &in.InstanceMix, &out.InstanceMix
		*out = new(InstanceMixSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Alerting != nil {
		in, out := &in.Alerting, &out.Alerting
		*out = new(AlertingSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FinancialPolicySpec.
func (in *FinancialPolicySpec) DeepCopy() *FinancialPolicySpec {
	if in == nil {
		return nil
	}
	out := new(FinancialPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FinancialPolicyStatus) DeepCopyInto(out *FinancialPolicyStatus) {
	*out = *in
	if in.LastEvaluated != nil {
		in, out := &in.LastEvaluated, &out.LastEvaluated
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]PolicyCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FinancialPolicyStatus.
func (in *FinancialPolicyStatus) DeepCopy() *FinancialPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(FinancialPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FinancialPolicy) DeepCopyInto(out *FinancialPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FinancialPolicy.
func (in *FinancialPolicy) DeepCopy() *FinancialPolicy {
	if in == nil {
		return nil
	}
	out := new(FinancialPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FinancialPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FinancialPolicyList) DeepCopyInto(out *FinancialPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FinancialPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FinancialPolicyList.
func (in *FinancialPolicyList) DeepCopy() *FinancialPolicyList {
	if in == nil {
		return nil
	}
	out := new(FinancialPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FinancialPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- CostReport deep copy ---

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostReportSpec) DeepCopyInto(out *CostReportSpec) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	in.EndTime.DeepCopyInto(&out.EndTime)
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostReportSpec.
func (in *CostReportSpec) DeepCopy() *CostReportSpec {
	if in == nil {
		return nil
	}
	out := new(CostReportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceCostSummary) DeepCopyInto(out *NamespaceCostSummary) {
	*out = *in
	if in.ByService != nil {
		in, out := &in.ByService, &out.ByService
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceCostSummary.
func (in *NamespaceCostSummary) DeepCopy() *NamespaceCostSummary {
	if in == nil {
		return nil
	}
	out := new(NamespaceCostSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamCostSummary) DeepCopyInto(out *TeamCostSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamCostSummary.
func (in *TeamCostSummary) DeepCopy() *TeamCostSummary {
	if in == nil {
		return nil
	}
	out := new(TeamCostSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostReportStatus) DeepCopyInto(out *CostReportStatus) {
	*out = *in
	if in.ByNamespace != nil {
		in, out := &in.ByNamespace, &out.ByNamespace
		*out = make([]NamespaceCostSummary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ByTeam != nil {
		in, out := &in.ByTeam, &out.ByTeam
		*out = make([]TeamCostSummary, len(*in))
		copy(*out, *in)
	}
	if in.GeneratedAt != nil {
		in, out := &in.GeneratedAt, &out.GeneratedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostReportStatus.
func (in *CostReportStatus) DeepCopy() *CostReportStatus {
	if in == nil {
		return nil
	}
	out := new(CostReportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostReport) DeepCopyInto(out *CostReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostReport.
func (in *CostReport) DeepCopy() *CostReport {
	if in == nil {
		return nil
	}
	out := new(CostReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CostReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostReportList) DeepCopyInto(out *CostReportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CostReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostReportList.
func (in *CostReportList) DeepCopy() *CostReportList {
	if in == nil {
		return nil
	}
	out := new(CostReportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CostReportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- OptimizationAction deep copy ---

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimizationActionSpec) DeepCopyInto(out *OptimizationActionSpec) {
	*out = *in
	if in.AffectedNodes != nil {
		in, out := &in.AffectedNodes, &out.AffectedNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CurrentMix != nil {
		in, out := &in.CurrentMix, &out.CurrentMix
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RecommendedMix != nil {
		in, out := &in.RecommendedMix, &out.RecommendedMix
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimizationActionSpec.
func (in *OptimizationActionSpec) DeepCopy() *OptimizationActionSpec {
	if in == nil {
		return nil
	}
	out := new(OptimizationActionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimizationActionStatus) DeepCopyInto(out *OptimizationActionStatus) {
	*out = *in
	if in.AppliedAt != nil {
		in, out := &in.AppliedAt, &out.AppliedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimizationActionStatus.
func (in *OptimizationActionStatus) DeepCopy() *OptimizationActionStatus {
	if in == nil {
		return nil
	}
	out := new(OptimizationActionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimizationAction) DeepCopyInto(out *OptimizationAction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimizationAction.
func (in *OptimizationAction) DeepCopy() *OptimizationAction {
	if in == nil {
		return nil
	}
	out := new(OptimizationAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OptimizationAction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimizationActionList) DeepCopyInto(out *OptimizationActionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OptimizationAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimizationActionList.
func (in *OptimizationActionList) DeepCopy() *OptimizationActionList {
	if in == nil {
		return nil
	}
	out := new(OptimizationActionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OptimizationActionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
